#!/usr/bin/env python3
"""Does a false positive's physical origin change what it costs, or only its rate?

A multipath ghost is not a random false alarm. It is generated by mirroring a
real object in a real surface, so its range and Doppler track a real parent
scan after scan. Random clutter is drawn fresh every scan with a new id. Both
are false detections; only one is temporally coherent.

That difference should matter at the tracker, because M-of-N confirmation is
exactly a coherence test: a detection that reappears inside the association
gates gets confirmed and held, one that does not gets deleted after a few
misses. So at an identical delivered false-detection rate the two classes
should reach the controller at very different rates.

This measures that, with no simulator. Everything is held fixed except the
origin of the false detections: same sensor config, same tracker, same scene,
same seed.

  python3 structured_vs_random_artefacts.py
  python3 structured_vs_random_artefacts.py --scans 8000 --seeds 13 14 15

Caveat worth keeping in view: the scene is scripted, so the ghost's azimuth is
chosen rather than solved from geometry. The sweep over azimuth is there to
show how much that choice decides, and it decides almost everything.
"""

import argparse
import math
import statistics

from radar.realistic_core import (
    IdealRadarTarget,
    RadarEnvironment,
    RealisticRadarModel,
    load_realistic_radar_config,
)

FALSE_SOURCES = ("ghost", "clutter")


def lead_vehicle(scan):
    """A car ahead, closing slowly, drifting slightly within the lane."""

    t = scan * 0.1
    return IdealRadarTarget(
        object_id=101, semantic_tag=14,
        distance_m=60.0 - 0.15 * (t % 200),
        azimuth_rad=0.01 * math.sin(0.2 * t),
        relative_velocity_mps=0.2, snr_db=22.0, point_count=6,
        lateral_extent_m=1.8, velocity_xy_mps=(0.2, 0.0), radial_extent_m=1.0,
    )


def guardrail():
    """The reflector the ghost bounces off."""

    return IdealRadarTarget(
        object_id=103, semantic_tag=3, distance_m=25.0, azimuth_rad=0.30,
        relative_velocity_mps=8.0, snr_db=25.0, point_count=10,
        lateral_extent_m=4.0, velocity_xy_mps=(8.0, 0.0), radial_extent_m=3.0,
    )


def mirror_ghost(scan, azimuth_rad):
    """The lead seen via the guardrail: range and Doppler tied to a real parent."""

    t = scan * 0.1
    parent_distance = lead_vehicle(scan).distance_m
    return IdealRadarTarget(
        object_id=-(10_000_000_000 + 101), semantic_tag=14,
        distance_m=parent_distance * 0.45,
        azimuth_rad=azimuth_rad + 0.004 * math.sin(0.2 * t),
        relative_velocity_mps=0.18, snr_db=15.0, point_count=3,
        lateral_extent_m=1.8, source="ghost", parent_object_id=101,
        reflector_id=103, bounce_type="mirror", bounce_order=2,
        path_length_m=parent_distance * 0.45,
        velocity_xy_mps=(0.18, 0.0), radial_extent_m=1.0,
    )


def measure(mode, clutter_rate, azimuth_rad, scans, seed):
    """Delivered false detections per scan, and how often one reached the controller."""

    config = load_realistic_radar_config(
        profile_name="rgd_regime_v1", max_range_m=100.0,
        overrides={"multipath_mode": mode, "false_alarms_per_scan": clutter_rate},
    )
    model = RealisticRadarModel(config=config, seed=seed)
    environment = RadarEnvironment()
    delivered = selected = 0
    for scan in range(scans):
        result = model.step(
            [lead_vehicle(scan), guardrail()],
            timestamp_s=scan * 0.05,
            environment=environment,
            multipath_targets=(
                [mirror_ghost(scan, azimuth_rad)] if mode == "geometry" else None
            ),
        )
        _, points = model.latest_points()
        delivered += sum(point.source in FALSE_SOURCES for point in points)
        if result.source in FALSE_SOURCES:
            selected += 1
    return delivered / scans, selected / scans


def averaged(seeds, **kwargs):
    rates, selections = zip(*(measure(seed=seed, **kwargs) for seed in seeds))
    return statistics.mean(rates), statistics.mean(selections)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--scans", type=int, default=4000)
    parser.add_argument("--seeds", type=int, nargs="+", default=[13])
    parser.add_argument("--clutter-rates", type=float, nargs="+",
                        default=[1.3, 3.0, 7.0, 12.0])
    parser.add_argument("--ghost-azimuths", type=float, nargs="+",
                        default=[0.0, 0.05, 0.15, 0.33],
                        help="radians; the path gate is roughly 1.8 m + 0.004 m/m")
    args = parser.parse_args()

    common = dict(scans=args.scans, seeds=args.seeds)
    print("=" * 82)
    print("STRUCTURED VS RANDOM FALSE POSITIVES, IDENTICAL TRACKER")
    print(f"  {args.scans} scans x {len(args.seeds)} seed(s), rgd_regime_v1, one lead car + guardrail")
    print("=" * 82)
    print(f"{"case":<44}{"false det/scan":>17}{"reached controller":>21}")
    print("-" * 82)

    structured = {}
    for azimuth in args.ghost_azimuths:
        rate, selected = averaged(mode="geometry", clutter_rate=0.0,
                                  azimuth_rad=azimuth, **common)
        structured[azimuth] = (rate, selected)
        print(f"{'multipath ghost, azimuth ' + format(azimuth, '.2f') + ' rad':<44}"
              f"{rate:>17.3f}{selected:>20.2%}")

    print()
    random_arm = {}
    for clutter_rate in args.clutter_rates:
        rate, selected = averaged(mode="off", clutter_rate=clutter_rate,
                                  azimuth_rad=0.0, **common)
        random_arm[clutter_rate] = (rate, selected)
        print(f"{'random clutter, rate ' + format(clutter_rate, '.1f'):<44}"
              f"{rate:>17.3f}{selected:>20.2%}")

    # Compare the in-path ghost against the clutter rate that delivers as many
    # false detections, which is the only honest comparison.
    in_path = min(structured)
    ghost_rate, ghost_selected = structured[in_path]
    matched = min(random_arm, key=lambda r: abs(random_arm[r][0] - ghost_rate))
    clutter_rate, clutter_selected = random_arm[matched]
    print("-" * 82)
    print(f"  rate-matched comparison at ~{ghost_rate:.2f} false detections/scan")
    print(f"    structured (in-path ghost)  reached the controller {ghost_selected:.2%} of scans")
    print(f"    random     (clutter {matched:.1f})      reached the controller {clutter_selected:.2%} of scans")
    if clutter_selected > 0:
        print(f"    ratio                       {ghost_selected / clutter_selected:.1f}x")
    print()
    print("  The azimuth sweep is the control: the same ghost outside the path gate")
    print("  reaches the controller on no scan at all, so this measures coherence")
    print("  only when the geometry puts the ghost in the ego's path.")
    print("=" * 82)


if __name__ == "__main__":
    main()
