%% run_matlab_radar.m -- MATLAB reference radar for the comparison pipeline.
%
% Consumes the shared ground truth (truth_scenario.csv, generated by
% generate_truth_scenario.py) and runs Radar Toolbox's statistical radar
% model, radarDataGenerator, configured to match the repository's
% rgd_regime_v1 envelope.  Writes matlab_detections.csv with the same schema
% as python_detections.csv so compare_models.py can score both against the
% same analytic truth.
%
% Requires: MATLAB + Radar Toolbox (install steps in compare_matlab/README.md).
% Run:
%   cd carla4/compare_matlab
%   matlab -batch "run('matlab/run_matlab_radar.m')"
%
% Conventions (must match generate_truth_scenario.py):
%   x forward, y RIGHT; azimuth from boresight, positive right;
%   radial velocity positive = CLOSING.  MATLAB reports opening-positive
%   range rate; it is flipped below via RANGE_RATE_SIGN.
%
% R2026b API notes (all four were verified empirically against this release,
% see the comments marked "R2026b:"):
%   1. radarDataGenerator takes TARGET POSES, not platforms.  The signature is
%      rdr(targetPoses, simTime); radarScenario/platform/waypointTrajectory
%      belong to radarSensor, not to this class.  There is no
%      (platforms, sensorPlatform, time) overload.
%   2. A pose struct needs Position plus one of PlatformID/ActorID/TruthID.
%      Build it by field assignment: struct('Position',[x y z],...) silently
%      expands to a struct ARRAY when the values are non-scalar, which
%      validates but then never detects anything.
%   3. RCSAzimuthAngles must span the full -180:180.  With a -90:90 window the
%      aspect-angle lookup misses and the target is never detected at all.
%   4. RCSPattern on a pose struct is in dBsm as given, NOT square metres, so
%      no 10^(dBsm/10) conversion.  Verified: the reported SNR tracks
%      (pattern - ReferenceRCS) exactly, e.g. pattern 2.512 against
%      ReferenceRCS 10 yields -7.49 dB, matching 2.512 - 10.

clear; clc;

% mfilename('fullpath') is documented to work for scripts run via run(), but
% older/edge invocations can return empty, which would silently reduce the CSV
% paths below to bare relative names.  Fall back to which(), then to pwd.
HERE = fileparts(mfilename('fullpath'));       % .../compare_matlab/matlab
if isempty(HERE)
    HERE = fileparts(which('run_matlab_radar.m'));
end
if isempty(HERE)
    HERE = fullfile(pwd, 'matlab');
end
BASE = fileparts(HERE);                        % .../compare_matlab
TRUTH_CSV = fullfile(BASE, 'truth_scenario.csv');
OUT_CSV   = fullfile(BASE, 'matlab_detections.csv');

% ---- Envelope: must match rgd_regime_v1 (+ 153 m RGD range gate) --------
FPS = 10;
MAX_RANGE_M = 153;
MAX_DOPPLER_MPS = 44.3;
RANGE_RES_M = 0.15;
AZ_RES_DEG = 1.8;
RR_RES_MPS = 0.087;
FOV_AZ_DEG = 140;
STOP_TIME = 38.5;

% RCS pattern grid.  Azimuth must span -180:180 (see note 3 above).
RCS_AZ_DEG = -180:1:180;
RCS_EL_DEG = [-90 90];

% ---- MATLAB detection model parameters ---------------------------------
PDETECT = 0.9;            % at REFERENCE_RANGE on REFERENCE_RCS
PFA = 1e-6;
REFERENCE_RANGE = 100;    % m
REFERENCE_RCS = 10;       % dBsm, = pedestrian RCS in the truth generator
GHOST_RCS_DBSM = 4;       % 10 dBsm - 6 dB bounce+material loss
% VERIFIED on R2026b: MATLAB reports +1.358 m/s for the pedestrian receding
% from the sensor while the closing-positive truth is -1.358 m/s, so -1 is
% correct.  compare_models.py prints the median bias as a regression check.
RANGE_RATE_SIGN = -1;
% MATLAB's built-in multipath (ground/two-ray reference; needs R2023a+).
ENABLE_MATLAB_MULTIPATH = false;

% Platform IDs used inside radarDataGenerator; must be positive and unique.
PID_PED = 1;
PID_GHOST = 2;

%% Ground truth -----------------------------------------------------------
if ~isfile(TRUTH_CSV)
    error(['truth_scenario.csv not found. Generate it first:\n' ...
           '  python3 carla4/compare_matlab/generate_truth_scenario.py']);
end
truth = readtable(TRUTH_CSV);
ped = truth(strcmp(truth.entity, 'pedestrian'), :);
ghost = truth(strcmp(truth.entity, 'mirror_type1_order2'), :);
fprintf('truth: %d pedestrian frames, %d ghost frames\n', ...
    height(ped), height(ghost));

% R2026b: build poses by field assignment so each stays a scalar struct, and
% index by frame so the loop below can look up position and velocity directly.
n_frames = min(height(ped), height(ghost));
if height(ped) ~= n_frames || height(ghost) ~= n_frames
    error('pedestrian and ghost truth must have the same frame count');
end

%% Radar: radarDataGenerator matched to rgd_regime_v1 ---------------------
% R2026b: MaxUnambiguousRange / MaxUnambiguousRadialSpeed only apply when
% HasRangeAmbiguities / HasRangeRateAmbiguities are enabled, and warn as
% "not relevant in this configuration" otherwise.  RangeLimits and
% RangeRateLimits are the properties that actually bound the reports, and
% they give the hard envelope (no wraparound) that compare_models.py checks.
radar = radarDataGenerator(1, 'No scanning', ...
    'UpdateRate', FPS, ...
    'MountingLocation', [0 0 0], ...
    'FieldOfView', [FOV_AZ_DEG 10], ...
    'RangeLimits', [0 MAX_RANGE_M], ...
    'RangeRateLimits', [-MAX_DOPPLER_MPS MAX_DOPPLER_MPS], ...
    'RangeResolution', RANGE_RES_M, ...
    'AzimuthResolution', AZ_RES_DEG, ...
    'RangeRateResolution', RR_RES_MPS, ...
    'HasRangeRate', true, ...
    'HasElevation', false, ...
    'HasNoise', true, ...
    'HasFalseAlarms', true, ...
    'DetectionProbability', PDETECT, ...
    'FalseAlarmRate', PFA, ...
    'ReferenceRange', REFERENCE_RANGE, ...
    'ReferenceRCS', REFERENCE_RCS, ...
    'DetectionCoordinates', 'Sensor spherical');

if ENABLE_MATLAB_MULTIPATH
    if isprop(radar, 'HasGhosts')
        radar.HasGhosts = true;
    else
        warning('HasGhosts not available in this release; disabled.');
    end
end

%% Simulation loop --------------------------------------------------------
fprintf('effective FOV %s, azimuth resolution %g deg, range-rate resolution %g m/s\n', ...
    mat2str(radar.EffectiveFieldOfView), radar.EffectiveAzimuthResolution, ...
    radar.RangeRateResolution);

rows = cell(0, 12);
n_reports = 0;
for f = 1:n_frames
    t = double(ped.time_s(f));

    pose_ped = struct();
    pose_ped.PlatformID = PID_PED;
    pose_ped.Position = [double(ped.x_m(f)), double(ped.y_m(f)), 0];
    pose_ped.Velocity = [double(ped.vx_mps(f)), double(ped.vy_mps(f)), 0];
    pose_ped.RCSPattern = REFERENCE_RCS * ones(numel(RCS_EL_DEG), numel(RCS_AZ_DEG));
    pose_ped.RCSAzimuthAngles = RCS_AZ_DEG;
    pose_ped.RCSElevationAngles = RCS_EL_DEG;

    % Analytic mirror-image ghost as a second target with reduced RCS, so both
    % models' ghost outputs are scored against the same analytic mirror truth.
    pose_ghost = struct();
    pose_ghost.PlatformID = PID_GHOST;
    pose_ghost.Position = [double(ghost.x_m(f)), double(ghost.y_m(f)), 0];
    pose_ghost.Velocity = [double(ghost.vx_mps(f)), double(ghost.vy_mps(f)), 0];
    pose_ghost.RCSPattern = GHOST_RCS_DBSM * ones(numel(RCS_EL_DEG), numel(RCS_AZ_DEG));
    pose_ghost.RCSAzimuthAngles = RCS_AZ_DEG;
    pose_ghost.RCSElevationAngles = RCS_EL_DEG;

    dets = radar([pose_ped pose_ghost], t);
    n_reports = n_reports + numel(dets);

    for k = 1:numel(dets)
        d = dets{k};
        m = d.Measurement(:);
        switch numel(m)
            case 4   % [az; el; range; range_rate]
                az = m(1); rng_m = m(3); rr = RANGE_RATE_SIGN * m(4);
            case 3   % [az; range; range_rate]  (HasElevation = false)
                az = m(1); rng_m = m(2); rr = RANGE_RATE_SIGN * m(3);
            otherwise
                error('unexpected Measurement length %d', numel(m));
        end
        attrs = d.ObjectAttributes;
        if iscell(attrs), attrs = attrs{1}; end
        if isfield(attrs, 'SNR'), snr_db = attrs.SNR; else, snr_db = NaN; end
        % R2026b: false alarms carry a negative TargetIndex; real targets carry
        % the PlatformID of the pose that produced them.
        switch attrs.TargetIndex
            case PID_PED,   ptype = 'direct';  oid = 1;
            case PID_GHOST, ptype = 'ghost';   oid = 2;
            otherwise,      ptype = 'clutter'; oid = 0;
        end
        rows(end + 1, :) = {'matlab_rgd_regime_v1', f, NaN, t, ...
            ptype, oid, rng_m * cosd(az), rng_m * sind(az), rng_m, ...
            az, rr, snr_db}; %#ok<SAGROW>
    end
end
fprintf('%d frames, %d reports\n', n_frames, n_reports);

%% Export -----------------------------------------------------------------
if isempty(rows)
    error('No detections produced. Check the radar() call above and doc radarDataGenerator.');
end
T = cell2table(rows, 'VariableNames', {'sensor', 'frame', 'source_scan_index', ...
    'time_s', 'point_type', 'object_id', 'x_m', 'y_m', 'range_m', ...
    'azimuth_deg', 'radial_velocity_mps', 'snr_db'});
T.frame = double(T.frame);
T.time_s = double(T.time_s);
T.object_id = double(T.object_id);
T.range_m = double(T.range_m);
T.azimuth_deg = double(T.azimuth_deg);
T.radial_velocity_mps = double(T.radial_velocity_mps);
T.snr_db = double(T.snr_db);
writetable(T, OUT_CSV);
fprintf('wrote %s (%d detections over %d frames)\n', OUT_CSV, height(T), n_frames);

% Classification sanity check: the export is useless if every report landed in
% 'clutter', so fail loudly rather than letting compare_models.py report an
% empty comparison.
fprintf('point budget: direct %d, ghost %d, clutter %d\n', ...
    sum(strcmp(T.point_type, 'direct')), sum(strcmp(T.point_type, 'ghost')), ...
    sum(strcmp(T.point_type, 'clutter')));

% Range-rate sign sanity check against truth (closing-positive).
direct = T(strcmp(T.point_type, 'direct'), :);
if ~isempty(direct)
    truth_rr = interp1(ped.frame, ped.radial_velocity_mps, direct.frame, 'nearest');
    med = median(direct.radial_velocity_mps - truth_rr, 'omitnan');
    fprintf('direct range-rate median error vs truth: %.3f m/s\n', med);
    if abs(med) > 0.5 * max(abs(ped.radial_velocity_mps))
        warning(['Range-rate sign likely flipped: set RANGE_RATE_SIGN = +1 ' ...
                 'at the top of this script and rerun.']);
    end
end